vivait_auth_logout:
    pattern: /logout

vivait_auth_login:
    pattern: /login
    defaults: { _controller: VivaitAuthBundle:Auth:login }

vivait_auth_authenticate:
    pattern: /authenticate

vivait_auth_user:
    pattern: /auth/users/
    defaults: { _controller: VivaitAuthBundle:User:index }

vivait_auth_user_edit:
    pattern: /auth/users/edit
    defaults: { _controller: VivaitAuthBundle:User:edit }

vivait_auth_user_delete:
    pattern: /auth/users/delete
    defaults: { _controller: VivaitAuthBundle:User:delete }

#vivait_auth_user_twofactor:
#    pattern: /user/twofactor
#    defaults: { _controller: VivaitAuthBundle:User:twofactor }
#
vivait_auth_group:
    pattern: /auth/groups/
    defaults: { _controller: VivaitAuthBundle:Group:index }

vivait_auth_group_edit:
    pattern: /auth/groups/edit
    defaults: { _controller: VivaitAuthBundle:Group:edit }

vivait_auth_group_delete:
    pattern: /auth/groups/delete
    defaults: { _controller: VivaitAuthBundle:Group:delete }

vivait_auth_changepassword:
    pattern: /auth/changepassword
    defaults: { _controller: VivaitAuthBundle:Auth:changepassword }

vivait_auth_changetenant:
    pattern: /auth/changetenant
    defaults: { _controller: VivaitAuthBundle:Auth:changetenant }

vivait_auth_heartbeat:
    pattern: /auth/heartbeat
    defaults: { _controller: VivaitAuthBundle:Auth:heartbeat }

vivait_auth_tenant:
    pattern: /auth/tenants/
    defaults: { _controller: VivaitAuthBundle:Tenant:index }

vivait_auth_tenant_edit:
    pattern: /auth/tenants/edit
    defaults: { _controller: VivaitAuthBundle:Tenant:edit }

vivait_auth_tenant_delete:
    pattern: /auth/tenants/delete
    defaults: { _controller: VivaitAuthBundle:Tenant:delete }

vivait_auth_impersonate:
    pattern: /auth/impersonate
    defaults: { _controller: VivaitAuthBundle:User:impersonate }

