security:
    encoders:
        Vivait\AuthBundle\Controller\UserController:
            algorithm:        sha512

        Vivait\AuthBundle\Controller\AuthController:
            algorithm:        sha512

        Vivait\AuthBundle\Entity\User:
            algorithm:        sha512

        Vivait\AuthBundle\Command\GenerateUserCommand:
            algorithm:        sha512

        Vivait\AuthBundle\Command\UserChangePasswordCommand:
            algorithm:        sha512
           
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        viva:
            entity: { class: Vivait\AuthBundle\Entity\User }

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: vivait_auth_authenticate
                login_path: vivait_auth_login
                always_use_default_target_path: true
                default_target_path: viva_app_homepage
            logout:
                path:   /logout
                target: /
            anonymous: ~
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_user }
            #http_basic:
            #    realm: "Secured System"

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: ROLE_USER }


#, requires_channel: https
