parameters:
#    vivait_auth.example.class: Vivait\AuthBundle\Example

services:
#    vivait_auth.example:
#        class: %vivait_auth.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

#services:
#    viva_user_provider:
#        class: "Vivait\AuthBundle\Entity\UserRepository"

    vivait_auth.tenant_manager:
        class: Vivait\AuthBundle\EventListener\TenantManager
        arguments: ['@security.context', '@logger', '@vivait_auth.repository.tenant']
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: vivait_auth }

    vivait_auth.repository.tenant:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - VivaitAuthBundle:Tenant

    vivait.settings.configure_menu_listener:
        class: Vivait\AuthBundle\EventListener\ConfigureMenuListener
        arguments: ['@security.context', '%vivait.auth.license_warning%']
        tags:
            - { name: kernel.event_listener, event: vivait.bootstrap.menu_configure, priority: -1, method: onMenuConfigure }